### ISSUE TITLE
requires unreleased (on CF) spinnery

### ISSUE THREAD

**Issue by Linguardium** [AshIndigo/CraftingStation#5]
version of spinnery required isnt actually a release version on CF. 
would you JiJ spinnery as a requirement to avoid users having to search for the github to get access to the maven link to get the version you use?

**Comment by AshIndigo** [comment]
Oops, I'll go fix that. Honestly it shouldn't need the latest version I just set that without realizing that the newest version wasn't on CF. Thanks!

New file is uploaded and waiting for approval now
